import {
  IExecuteFunctions,
  INodeExecutionData,
  INodeType,
  INodeTypeDescription,
  NodeOperationError,
} from 'n8n-workflow';
import oracledb, { Connection } from 'oracledb';

import { OracleConnectionPool } from './core';

/**
 * Nomes de identificadores Oracle (tabelas, índices, constraints) só podem
 * conter letras, números e underscore, e devem começar com letra.
 * Isso também evita injeção via interpolação direta de tableName no SQL.
 */
const IDENTIFIER_REGEX = /^[A-Za-z][A-Za-z0-9_]{0,29}$/;

function assertValidIdentifier(node: any, value: string, fieldLabel: string): void {
  if (!IDENTIFIER_REGEX.test(value)) {
    throw new NodeOperationError(
      node,
      `${fieldLabel} inválido: "${value}". Use apenas letras, números e underscore, ` +
        'começando com uma letra (máx. 30 caracteres).',
    );
  }
}

export class OracleChatMemoryOperations {
  private executeFunctions: IExecuteFunctions;

  constructor(executeFunctions: IExecuteFunctions) {
    this.executeFunctions = executeFunctions;
  }

  private get node() {
    return this.executeFunctions.getNode();
  }

  async setupTable(
    connection: Connection,
    tableName: string,
  ): Promise<INodeExecutionData[]> {
    assertValidIdentifier(this.node, tableName, 'Table Name');

    try {
      // Nomes de constraint/índice namespaced pela tabela: no Oracle esses
      // nomes são únicos POR SCHEMA, não por tabela. Sem o prefixo, criar
      // uma segunda tabela via este node (schema compartilhado) falharia
      // com ORA-02264 (constraint name already used).
      const constraintName = `chk_${tableName}_msg_type`.substring(0, 30);
      const indexName = `idx_${tableName}_session`.substring(0, 30);

      const createTableSQL = `
        BEGIN
          EXECUTE IMMEDIATE '
            CREATE TABLE ${tableName} (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              session_id VARCHAR2(255) NOT NULL,
              message_type VARCHAR2(50) NOT NULL,
              content CLOB NOT NULL,
              timestamp_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              metadata CLOB,
              CONSTRAINT ${constraintName} CHECK (message_type IN (''user'', ''assistant'', ''system''))
            )
          ';
        EXCEPTION
          WHEN OTHERS THEN
            IF SQLCODE = -955 THEN
              NULL; -- Tabela já existe, segue normalmente
            ELSE
              RAISE;
            END IF;
        END;
      `;

      await connection.execute(createTableSQL);

      const createIndexSQL = `
        BEGIN
          EXECUTE IMMEDIATE 'CREATE INDEX ${indexName} ON ${tableName}(session_id)';
        EXCEPTION
          WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
              RAISE;
            END IF;
        END;
      `;

      await connection.execute(createIndexSQL);
      await connection.commit();

      return this.executeFunctions.helpers.returnJsonArray([
        {
          success: true,
          message: `Tabela ${tableName} configurada com sucesso`,
          operation: 'setup',
        },
      ]);
    } catch (error: unknown) {
      throw new NodeOperationError(
        this.node,
        `Erro ao configurar tabela: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }

  /**
   * Processa uma mensagem para um item específico do input (por índice),
   * em vez de sempre olhar inputData[0]. Isso permite que o node receba
   * múltiplos itens (ex: vindos de um loop/Split in Batches) e grave todos,
   * não apenas o primeiro.
   */
  async addMessage(
    connection: Connection,
    sessionId: string,
    tableName: string,
    memoryType: string,
    itemIndex: number,
  ): Promise<INodeExecutionData> {
    assertValidIdentifier(this.node, tableName, 'Table Name');

    try {
      const items = this.executeFunctions.getInputData();
      const messageData = items[itemIndex]?.json;

      if (!messageData) {
        throw new Error(`Nenhum dado de mensagem fornecido no input (item ${itemIndex})`);
      }

      const content =
        messageData.content != null
          ? String(messageData.content)
          : messageData.message != null
            ? String(messageData.message)
            : JSON.stringify(messageData);

      const metadataObj =
        messageData && typeof messageData.metadata === 'object' && messageData.metadata !== null
          ? messageData.metadata
          : {};

      const metadata = JSON.stringify({
        timestamp: new Date().toISOString(),
        nodeId: this.node.parameters.id,
        ...metadataObj,
      });

      const insertSQL = `
        INSERT INTO ${tableName} (session_id, message_type, content, metadata)
        VALUES (:sessionId, :messageType, :content, :metadata)
      `;

      const result = await connection.execute(
        insertSQL,
        {
          sessionId: String(sessionId),
          messageType: String(memoryType),
          content,
          metadata,
        },
        { autoCommit: true },
      );

      return {
        json: {
          success: true,
          sessionId,
          messageType: memoryType,
          content,
          rowsAffected: result.rowsAffected,
          operation: 'addMessage',
        },
      };
    } catch (error: unknown) {
      throw new NodeOperationError(
        this.node,
        `Erro ao adicionar mensagem (item ${itemIndex}): ${
          error instanceof Error ? error.message : String(error)
        }`,
        { itemIndex },
      );
    }
  }

  async getMessages(
    connection: Connection,
    sessionId: string,
    tableName: string,
  ): Promise<INodeExecutionData[]> {
    assertValidIdentifier(this.node, tableName, 'Table Name');

    try {
      const selectSQL = `
        SELECT
          id,
          session_id,
          message_type,
          content,
          timestamp_created,
          metadata
        FROM ${tableName}
        WHERE session_id = :sessionId
        ORDER BY timestamp_created ASC
      `;

      const result = await connection.execute(
        selectSQL,
        { sessionId },
        {
          outFormat: oracledb.OUT_FORMAT_OBJECT,
          // Força CLOB (content/metadata) a virem como string em vez de
          // objeto Lob/stream. Isso é feito aqui explicitamente para não
          // depender de uma configuração global (oracledb.fetchAsString)
          // estar (ou não) setada no OracleConnectionPool.
          fetchInfo: {
            CONTENT: { type: oracledb.STRING },
            METADATA: { type: oracledb.STRING },
          },
        },
      );

      const messages = (result.rows as any[]).map(row => {
        let parsedMetadata: Record<string, unknown> | null = null;
        if (row.METADATA) {
          try {
            parsedMetadata = JSON.parse(row.METADATA);
          } catch {
            // metadata corrompido/malformado: não derruba a leitura inteira
            parsedMetadata = { _raw: row.METADATA, _parseError: true };
          }
        }

        return {
          id: row.ID,
          sessionId: row.SESSION_ID,
          messageType: row.MESSAGE_TYPE,
          content: row.CONTENT,
          timestamp: row.TIMESTAMP_CREATED,
          metadata: parsedMetadata,
        };
      });

      return this.executeFunctions.helpers.returnJsonArray(messages);
    } catch (error: unknown) {
      throw new NodeOperationError(
        this.node,
        `Erro ao recuperar mensagens: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }

  async clearMemory(
    connection: Connection,
    sessionId: string,
    tableName: string,
  ): Promise<INodeExecutionData[]> {
    assertValidIdentifier(this.node, tableName, 'Table Name');

    try {
      const deleteSQL = `DELETE FROM ${tableName} WHERE session_id = :sessionId`;

      const result = await connection.execute(
        deleteSQL,
        { sessionId },
        {
          autoCommit: true,
        },
      );

      return this.executeFunctions.helpers.returnJsonArray([
        {
          success: true,
          sessionId,
          messagesDeleted: result.rowsAffected,
          operation: 'clearMemory',
        },
      ]);
    } catch (error: unknown) {
      throw new NodeOperationError(
        this.node,
        `Erro ao limpar memória: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }

  async getSummary(
    connection: Connection,
    sessionId: string,
    tableName: string,
  ): Promise<INodeExecutionData[]> {
    assertValidIdentifier(this.node, tableName, 'Table Name');

    try {
      const summarySQL = `
        SELECT
          COUNT(*) as total_messages,
          COUNT(CASE WHEN message_type = 'user' THEN 1 END) as user_messages,
          COUNT(CASE WHEN message_type = 'assistant' THEN 1 END) as assistant_messages,
          COUNT(CASE WHEN message_type = 'system' THEN 1 END) as system_messages,
          MIN(timestamp_created) as first_message,
          MAX(timestamp_created) as last_message
        FROM ${tableName}
        WHERE session_id = :sessionId
      `;

      const result = await connection.execute(
        summarySQL,
        { sessionId },
        {
          outFormat: oracledb.OUT_FORMAT_OBJECT,
        },
      );

      const summary = result.rows?.[0] as any;

      return this.executeFunctions.helpers.returnJsonArray([
        {
          sessionId,
          totalMessages: summary?.TOTAL_MESSAGES || 0,
          userMessages: summary?.USER_MESSAGES || 0,
          assistantMessages: summary?.ASSISTANT_MESSAGES || 0,
          systemMessages: summary?.SYSTEM_MESSAGES || 0,
          firstMessage: summary?.FIRST_MESSAGE,
          lastMessage: summary?.LAST_MESSAGE,
          operation: 'getSummary',
        },
      ]);
    } catch (error: unknown) {
      throw new NodeOperationError(
        this.node,
        `Erro ao obter resumo: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }
}

export class OracleChatMemory implements INodeType {
  description: INodeTypeDescription = {
    displayName: 'Oracle Chat Memory',
    name: 'oracleChatMemory',
    icon: 'file:oracle.svg',
    group: ['transform'],
    version: 1,
    description: 'Gerenciamento de memória de chat usando Oracle Database',
    defaults: {
      name: 'Oracle Chat Memory',
    },
    inputs: ['main'],
    outputs: ['main'],
    credentials: [
      {
        name: 'oracleCredentials',
        required: true,
      },
    ],
    properties: [
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        default: 'addMessage',
        options: [
          { name: 'Setup Table', value: 'setup' },
          { name: 'Add Message', value: 'addMessage' },
          { name: 'Get Messages', value: 'getMessages' },
          { name: 'Clear Memory', value: 'clearMemory' },
          { name: 'Get Summary', value: 'getSummary' },
        ],
        description: 'Operação a ser executada',
      },
      {
        displayName: 'Session ID',
        name: 'sessionId',
        type: 'string',
        default: '',
        description: 'ID único da sessão de chat',
        displayOptions: {
          hide: {
            operation: ['setup'],
          },
        },
      },
      {
        displayName: 'Memory Type',
        name: 'memoryType',
        type: 'options',
        default: 'user',
        options: [
          { name: 'User Message', value: 'user' },
          { name: 'Assistant Message', value: 'assistant' },
          { name: 'System Message', value: 'system' },
        ],
        description: 'Tipo da mensagem',
        displayOptions: {
          show: {
            operation: ['addMessage'],
          },
        },
      },
      {
        displayName: 'Table Name',
        name: 'tableName',
        type: 'string',
        default: 'CHAT_MEMORY',
        description:
          'Nome da tabela para armazenar as mensagens (apenas letras, números e underscore)',
      },
    ],
  };

  async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
    const credentials = await this.getCredentials('oracleCredentials');

    const oracleCredentials = {
      user: String(credentials.user),
      password: String(credentials.password),
      connectionString: String(credentials.connectionString),
      thinMode: credentials.thinMode !== false,
      libDir: credentials.libDir ? String(credentials.libDir) : undefined,
      configDir: credentials.configDir ? String(credentials.configDir) : undefined,
      errorUrl: credentials.errorUrl ? String(credentials.errorUrl) : undefined,
    };

    const items = this.getInputData();
    // Operações não incrementais (mesma tabela/sessão pra toda a execução)
    // ainda usam o item 0 como referência de parâmetros, mas addMessage
    // agora processa TODOS os itens de input, não só o primeiro.
    const operation = this.getNodeParameter('operation', 0) as string;

    let connection: Connection | undefined;
    let returnData: INodeExecutionData[] = [];
    const chatMemoryOps = new OracleChatMemoryOperations(this);

    try {
      const pool = await OracleConnectionPool.getPool(oracleCredentials);
      connection = await pool.getConnection();

      switch (operation) {
        case 'setup': {
          const tableName = this.getNodeParameter('tableName', 0) as string;
          returnData = await chatMemoryOps.setupTable(connection, tableName);
          break;
        }
        case 'addMessage': {
          // Processa cada item de input individualmente: sessionId,
          // tableName e memoryType podem ser expressions diferentes
          // por item (ex: vindo de dados anteriores no workflow).
          for (let i = 0; i < items.length; i++) {
            const sessionId = this.getNodeParameter('sessionId', i) as string;
            const tableName = this.getNodeParameter('tableName', i) as string;
            const memoryType = this.getNodeParameter('memoryType', i) as string;

            const itemResult = await chatMemoryOps.addMessage(
              connection,
              sessionId,
              tableName,
              memoryType,
              i,
            );
            returnData.push(itemResult);
          }
          break;
        }
        case 'getMessages': {
          const sessionId = this.getNodeParameter('sessionId', 0) as string;
          const tableName = this.getNodeParameter('tableName', 0) as string;
          returnData = await chatMemoryOps.getMessages(connection, sessionId, tableName);
          break;
        }
        case 'clearMemory': {
          const sessionId = this.getNodeParameter('sessionId', 0) as string;
          const tableName = this.getNodeParameter('tableName', 0) as string;
          returnData = await chatMemoryOps.clearMemory(connection, sessionId, tableName);
          break;
        }
        case 'getSummary': {
          const sessionId = this.getNodeParameter('sessionId', 0) as string;
          const tableName = this.getNodeParameter('tableName', 0) as string;
          returnData = await chatMemoryOps.getSummary(connection, sessionId, tableName);
          break;
        }
        default:
          throw new NodeOperationError(this.getNode(), `Operação "${operation}" não suportada`);
      }
    } catch (error) {
      if (error instanceof NodeOperationError) {
        throw error;
      }
      throw new NodeOperationError(this.getNode(), `Chat Memory Error: ${error}`);
    } finally {
      if (connection) {
        await connection.close();
      }
    }

    return [returnData];
  }
}