/* eslint-disable n8n-nodes-base/node-filename-for-env-issue */

import {
	IExecuteFunctions,
	INode,
	INodeType,
	INodeTypeDescription,
	NodeOperationError,
} from 'n8n-workflow';
import oracledb, { Connection, Pool } from 'oracledb';
import {
	AIMessage,
	BaseMessage,
	HumanMessage,
	SystemMessage,
	StoredMessage,
	mapStoredMessageToChatMessage,
} from '@langchain/core/messages';
import { BaseMemory, getInputValue } from '@langchain/core/memory';

import { OracleConnectionPool, OracleCredentials } from './core';

const IDENTIFIER_REGEX = /^[A-Za-z][A-Za-z0-9_]{0,127}$/;

function assertValidIdentifier(value: string, fieldLabel: string, node: INode): void {
	if (!IDENTIFIER_REGEX.test(value)) {
		throw new NodeOperationError(
			node,
			`${fieldLabel} inválido: "${value}". Use apenas letras, números e underscore, começando com uma letra.`,
		);
	}
}

interface OracleChatMemoryConfig {
	pool: Pool;
	sessionId: string;
	tableName?: string;
	contextWindowLength?: number;
}

export class OracleChatMessageHistory extends BaseMemory {
	lc_serializable = false;

	private pool: Pool;
	private sessionId: string;
	private tableName: string;
	private contextWindowLength?: number;
	private isTableSetup: boolean = false;
	private node: INode;

	constructor(
		config: OracleChatMemoryConfig & {
			node: INode;
		},
	) {
		super();
		this.pool = config.pool;
		this.sessionId = config.sessionId;
		this.tableName = config.tableName ?? 'N8N_CHAT_MEMORY';
		this.contextWindowLength = config.contextWindowLength;
		this.node = config.node;
	}

	private async ensureTable(): Promise<void> {
		if (this.isTableSetup) {
			return;
		}

		assertValidIdentifier(this.tableName, 'Table Name', this.node);

		let connection: Connection | undefined;
		try {
			connection = await this.pool.getConnection();
			const constraintName = `chk_${this.tableName}_msg_type`.substring(0, 128);
			const indexName = `idx_${this.tableName}_session`.substring(0, 128);

			const createTableSQL = `
        BEGIN
          EXECUTE IMMEDIATE '
            CREATE TABLE ${this.tableName} (
              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              session_id VARCHAR2(255) NOT NULL,
              message_type VARCHAR2(50) NOT NULL,
              content CLOB NOT NULL,
              timestamp_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              metadata CLOB,
              CONSTRAINT ${constraintName} CHECK (message_type IN (''human'', ''ai'', ''system''))
            )
          ';
        EXCEPTION
          WHEN OTHERS THEN
            IF SQLCODE = -955 THEN NULL;
            ELSE RAISE;
            END IF;
        END;
      `;

			const createIndexSQL = `
        BEGIN
          EXECUTE IMMEDIATE 'CREATE INDEX ${indexName} ON ${this.tableName}(session_id)';
        EXCEPTION
          WHEN OTHERS THEN
            IF SQLCODE != -955 AND SQLCODE != -1408 THEN NULL;
            ELSE RAISE;
            END IF;
        END;
      `;

			await connection.execute(createTableSQL);
			await connection.execute(createIndexSQL);
			await connection.commit();
			this.isTableSetup = true;
		} finally {
			await connection?.close();
		}
	}

	async getMessages(): Promise<BaseMessage[]> {
		let connection: Connection | undefined;
		try {
			connection = await this.pool.getConnection();

			let selectSQL = `
				SELECT message_type, content, metadata
				FROM (
						SELECT message_type, content, metadata, timestamp_created
						FROM ${this.tableName}
						WHERE session_id = :sessionId
						ORDER BY timestamp_created DESC
				)
			`;

			if (this.contextWindowLength !== undefined && this.contextWindowLength > 0) {
				selectSQL += ` FETCH FIRST ${this.contextWindowLength * 2} ROWS ONLY`;
			}

			const result = await connection.execute<{
				MESSAGE_TYPE: string;
				CONTENT: string;
				METADATA: string;
			}>(
				selectSQL,
				{ sessionId: this.sessionId },
				{
					outFormat: oracledb.OUT_FORMAT_OBJECT,
					fetchInfo: {
						CONTENT: { type: oracledb.STRING },
						METADATA: { type: oracledb.STRING },
					},
				},
			);

			const messages = (result.rows ?? []).map((row) => {
				const additional_kwargs = row.METADATA ? JSON.parse(row.METADATA) : {};
				switch (row.MESSAGE_TYPE) {
					case 'human':
						return new HumanMessage({ content: row.CONTENT, additional_kwargs });
					case 'ai':
						return new AIMessage({ content: row.CONTENT, additional_kwargs });
					case 'system':
						return new SystemMessage({ content: row.CONTENT, additional_kwargs });
					default:
						// Fallback for unknown types, though the DB constraint should prevent this
						return new HumanMessage({ content: row.CONTENT, additional_kwargs });
				}
			});

			return messages.reverse(); // Restore chronological order
		} finally {
			await connection?.close();
		}
	}

	async addMessage(message: BaseMessage): Promise<void> {
		await this.ensureTable();

		let connection: Connection | undefined;
		try {
			connection = await this.pool.getConnection();
			const messageType = message._getType();
			const content = getInputValue(message);
			const metadata = JSON.stringify(message.additional_kwargs ?? {});

			const insertSQL = `
        INSERT INTO ${this.tableName} (session_id, message_type, content, metadata)
        VALUES (:sessionId, :messageType, :content, :metadata)
      `;

			await connection.execute(
				insertSQL,
				{
					sessionId: this.sessionId,
					messageType,
					content,
					metadata,
				},
				{ autoCommit: true },
			);
		} finally {
			await connection?.close();
		}
	}

	async clear(): Promise<void> {
		await this.ensureTable();
		let connection: Connection | undefined;
		try {
			connection = await this.pool.getConnection();
			const deleteSQL = `DELETE FROM ${this.tableName} WHERE session_id = :sessionId`;
			await connection.execute(deleteSQL, { sessionId: this.sessionId }, { autoCommit: true });
		} finally {
			await connection?.close();
		}
	}

	get memoryKeys(): string[] {
		return [];
	}

	async loadMemoryVariables(_values: Record<string, any>): Promise<Record<string, any>> {
		const messages = await this.getMessages();
		return {
			chat_history: messages,
		};
	}

	async saveContext(_inputs: Record<string, any>, outputs: Record<string, any>): Promise<void> {
		const humanMessage = new HumanMessage({
			content: getInputValue(_inputs.input),
			additional_kwargs: _inputs.options ?? {},
		});
		const aiMessage = new AIMessage({
			content: getInputValue(outputs.output),
			additional_kwargs: outputs.options ?? {},
		});

		await this.addMessage(humanMessage);
		await this.addMessage(aiMessage);
	}
}

export class ChatMemory implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'Oracle Chat Memory',
		name: 'oracleChatMemory',
		icon: 'file:oracle.svg',
		group: ['ai', 'memory'],
		version: 1,
		description: 'Usa uma tabela Oracle para persistir a memória de chat',
		defaults: {
			name: 'Oracle Memory',
		},
		inputs: [],
		outputs: ['main'],
		credentials: [
			{
				name: 'oracleCredentials',
				required: true,
			},
		],
		properties: [
			{
				displayName: 'Session Key',
				name: 'sessionId',
				type: 'string',
				default: '{{ $json.user }}_{{ $json.chatId }}',
				description:
					'Identificador único da sessão de chat. Use expressões para criar chaves dinâmicas (ex: por usuário).',
			},
			{
				displayName: 'Table Name',
				name: 'tableName',
				type: 'string',
				default: 'N8N_CHAT_MEMORY',
				description:
					'Nome da tabela para armazenar as mensagens. Será criada automaticamente se não existir.',
			},
			{
				displayName: 'Context Window Length',
				name: 'contextWindowLength',
				type: 'number',
				typeOptions: {
					minValue: 1,
				},
				default: 10,
				description:
					'Número de interações (pares de mensagens) a serem recuperadas. Ex: 10 significa 10 mensagens do usuário e 10 da IA.',
			},
		],
	};

	async execute(this: IExecuteFunctions): Promise<any> {
		const creds = await this.getCredentials('oracleCredentials');

		const oracleCredentials = {
			user: creds.user as string,
			password: creds.password as string,
			host: creds.host as string,
			port: creds.port as number,
			serviceName: creds.serviceName as string,
			connectionString: creds.connectionString as string,
			thinMode: creds.thinMode as boolean,
		};

		const sessionId = this.getNodeParameter('sessionId', 0) as string;
		const tableName = this.getNodeParameter('tableName', 0) as string;
		const contextWindowLength = this.getNodeParameter('contextWindowLength', 0) as
			| number
			| undefined;

		const node = this.getNode();

		if (!sessionId) {
			throw new NodeOperationError(node, 'O Session Key é obrigatório para a memória do chat.');
		}

		try {
			const pool = await OracleConnectionPool.getPool(oracleCredentials);

			const memory = new OracleChatMessageHistory({
				pool,
				sessionId,
				tableName,
				contextWindowLength,
				node,
			});

			return {
				main: [[{ json: { memory } }]],
			};
		} catch (error) {
			if (error instanceof NodeOperationError) {
				throw error;
			}
			throw new NodeOperationError(this.getNode(), `Chat Memory Error: ${error}`);
		}
	}
}